logo_title: GEEK kang

style: black

favicon: /favicon.ico

menu:
  Home: /
  Archive: /archives
  Category: /categories
  Tag: /tags
  Github: https://github.com/fujikang

# 做了域名限制，请改成自己的 KEY
# 若关闭valine 设置enable为false
valine:
  enable: true
  appId: CmCti21ooOOIzFOhEyFkFvR0-gzGzoHsz
  appKey: FqiyUqbg7McKN2eG0MCewupf

highlight:
  enable: false